### ISSUE TITLE
关于配置文件ini的处理

### ISSUE THREAD

**Issue by wideweide** [linxinhong/VimDesktop#1]
鉴于vimd主要以源码的形式供使用，而每个用户基本都会修改ini，为方便源码管理，因此对配置文件建议如下操作：
- 默认不提供ini文件，即无需配置文件也可以运行
- 如确实需要，由vimd和插件自行生成所需ini文件
- 将ini文件加入全局忽略列表

另外就是：我倾向于将所有配置信息统一放置到vimd.ini中，不用分散到各处。当然分散有分散的好处....

**Comment by linxinhong** [comment]
解决如下：
- 提供一个 Sample.ini ，在VimD运行的时候，发现没有vimd.ini的话，自动复制一份sample.ini到 vimd.ini。并加载 sample.ini 不涉及热键配置，主要起说明作用。
- 不提供vimd.ini
- 我也倾向于使用单独ini，这样用户备份会方便些。类似vim

**Comment by linxinhong** [comment]
#### 配置文件准备使用 [Yaml](http://www.ibm.com/developerworks/cn/xml/x-cn-yamlintro/index.html) 格式

``` yaml
# 全局配置部分
config: 
  option1: ""
  option2: ""
# 插件管理，用于启用或者禁用插件
plugin: 
  p1: true
  p2: true
  p3: false
# 用于设置排除窗口，此段下的窗口无视vimd
exclude: 
  记事本: 
    class: Notepad
    filepath: notepad.exe
    title: 记事本
# 热键映射
keymap: 
  global: 
    normal:
      j: <down>
    insert: 
      <esc>: <Up>
  资源管理器: 
    set: 
      class: CabinetWClass
      timeout: 800
      maxcount: 100
      info: True
    normal: 
      i: <gen_insertMode>
      j: <down>
      k: <Up>
      h: <Left>
      l: <Right>
    insert: 
      <esc>: <gen_normalMode>
# 插件可以在配置文件添加自定义段
totalcmd: 
  TCDir: "e:\\Program Files\\totalcmd\\"
  TCExe: Totalcmd.exe
  sb: 1
  sb_len: 200
everything: 
  exe: E:\everything\everything.exe
```
